## <font color="blue">About the data</font>
- The file **grocery_data.csv** lists the monthly prices of Apple, Banana, Grapes, Mango, and Water Melons from January to October 2022.
- Your task is to fill in the missing values according to the given instructions.

In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'fruits_data.csv' into the dataframe 'df'.
- show the number of rows and columns in it.
- list all the columns present in the dataframe.
- show the dataframe

In [2]:
#read the csv file
df=pd.read_csv("grocery_data.csv")

#show the number of rows and columns
df.shape

#list all the columns


#show the dataframe

(10, 6)

In [3]:
df.columns

Index(['date', 'milk(1L)', 'bread(1 loaf)', 'tomato(1kg)', 'rice(1kg)',
       'cooking oil(1L)'],
      dtype='object')

In [4]:
df

,date,milk(1L),bread(1 loaf),tomato(1kg),rice(1kg),cooking oil(1L)
0,02-01-2022,58.0,35.0,72.0,48.0,155.0
1,02-02-2022,60.0,NaN,74.0,NaN,157.0
2,02-03-2022,NaN,36.0,73.0,50.0,NaN
3,02-04-2022,62.0,37.0,NaN,49.0,160.0
4,02-05-2022,61.0,35.0,75.0,51.0,158.0
5,02-06-2022,59.0,34.0,76.0,NaN,159.0
6,02-07-2022,NaN,36.0,74.0,52.0,NaN
7,02-08-2022,63.0,NaN,73.0,53.0,161.0
8,02-09-2022,64.0,38.0,NaN,51.0,162.0
9,02-10-2022,62.0,37.0,77.0,50.0,160.0

### <font color="purple">**Question2**</font>
- Fill all the null values in the dataframe with '-1' and store the result to variable 'new_df'.

In [5]:
#fill null values with -1 and store it to 'new_df'
new_df=df.fillna(-1)

#show the dataframe 'new_df'
new_df

,date,milk(1L),bread(1 loaf),tomato(1kg),rice(1kg),cooking oil(1L)
0,02-01-2022,58.0,35.0,72.0,48.0,155.0
1,02-02-2022,60.0,-1.0,74.0,-1.0,157.0
2,02-03-2022,-1.0,36.0,73.0,50.0,-1.0
3,02-04-2022,62.0,37.0,-1.0,49.0,160.0
4,02-05-2022,61.0,35.0,75.0,51.0,158.0
5,02-06-2022,59.0,34.0,76.0,-1.0,159.0
6,02-07-2022,-1.0,36.0,74.0,52.0,-1.0
7,02-08-2022,63.0,-1.0,73.0,53.0,161.0
8,02-09-2022,64.0,38.0,-1.0,51.0,162.0
9,02-10-2022,62.0,37.0,77.0,50.0,160.0

### <font color="purple">**Question3**</font>
Fill the null values in respective columns like below:

    - milk(1L): Mean value of that column
    - bread(1 loaf) Mean value of that column
    - tomato(1kg): Median value of that column
    - rice(1kg): Median value of that column
    - Water Melons(1): Fill null values with "Not Available".
    
Finally store the output to 'new_df' variable

In [6]:
#write the code to fill null values as per above condition
#store the result to 'new_df' variable
new_df=df.fillna({'milk(1L)':df['milk(1L)'].mean(),
                  'bread(1 loaf)':df['bread(1 loaf)'].mean(),
                  'tomato(1kg)':df['tomato(1kg)'].median(),
                  'rice(1kg)':df['rice(1kg)'].median(),
                  'Water Melons(1)':"Not Available"})

#show the dataframe 'new_df'
new_df

KeyError: 'apple(1kg)'

### <font color="purple">**Question4**</font>

- Fill the null values with the non-null value before it (Forward fill method)
- Store the result in 'new_df'.

In [ ]:
#fill null values using 'ffill'
new_df=df.ffill()

#show the dataframe 'new_df'
new_df

### <font color="purple">**Question5**</font>
- Drop the rows if it does not contain atleast 4 non-null values (use the concept of thresholding).
- store the result in 'new_df'

In [ ]:
#write the code here
new_df=df.dropna(thresh=4)

#show the dataframe 'new_df'
new_df

### <font color="purple">**Question6**</font>


- Finally, remove the row if it contain null value and store the result in 'new_df'
- save that dataframe to csv:'final_data.csv' and make sure to set index to False

In [ ]:
#write the code here
new_df=df.dropna()


#show the dataframe 'new_df'
new_df

In [ ]:
#save the dataframe to 'final_data.csv'
new_df.to_csv('final_data.csv')